update smtx version to match custom

diff --git a/tests/scripts/slamp-driver b/tests/scripts/slamp-driver
--- a/tests/scripts/slamp-driver
+++ b/tests/scripts/slamp-driver
@@ -45,7 +45,8 @@ function drive {
      -load $LIBERTY_LIBS_DIR/libSLAMP.so
      -basic-loop-aa -scev-loop-aa -auto-restrict-aa -intrinsic-aa -global-malloc-aa -pure-fun-aa -semi-local-fun-aa -phi-maze-aa -no-capture-global-aa -no-capture-src-aa -type-aa -no-escape-fields-aa -acyclic-aa -disjoint-fields-aa -field-malloc-aa -loop-variant-allocation-aa -std-in-out-err-aa -array-of-structures-aa -kill-flow-aa -callsite-depth-combinator-aa -unique-access-paths-aa $EXTRA -llvm-aa-results  -pdgbuilder "
 
-  local SLAMP_HOOKS="$LIBERTY_LIBS_DIR/libslamp_hooks_stats.a"
+  # local SLAMP_HOOKS="$LIBERTY_LIBS_DIR/libslamp_hooks_stats.a"
+  local SLAMP_HOOKS="/u/NAS_SCRATCH/ziyangx/cpf-workspace-9-master/build/cpf-build-release/lib/SLAMP/SLAMPcustom/libslamp_hooks_custom.a"
   local SLAMP_OUTFILE="$2-$3.result.slamp.profile"
 
  local OPTS="-slamp-insts -slamp-target-fn=$2 -slamp-target-loop=$3 $EXTRA_FLAGS -slamp-outfile=$SLAMP_OUTFILE"
@@ -76,7 +77,8 @@ function drive {
   # local CMD3="clang++ -no-pie  -O2 $PRELINK_OBJ $SLAMP_HOOKS -o $EXE -g $DEFAULT_LDFLAGS -lunwind $DEFAULT_LIBS -ldl -lutil" 
   #local CMD3="g++ -Og $PRELINK_OBJ $SLAMP_HOOKS -o $EXE -g $DEFAULT_LDFLAGS -lunwind $DEFAULT_LIBS -ldl -lutil" 
 
-  RAW_CMD3="clang++ -no-pie  -O2 $PRELINK_OBJ $SLAMP_HOOKS -g $LINKING_OPTS -lunwind $DEFAULT_LIBS -ldl -lutil" 
+  # RAW_CMD3="clang++ -no-pie  -O2 $PRELINK_OBJ $SLAMP_HOOKS -g $LINKING_OPTS -lunwind $DEFAULT_LIBS -ldl -lutil" 
+  RAW_CMD3="clang++ -no-pie  -O2 $PRELINK_OBJ $SLAMP_HOOKS -g $LINKING_OPTS -lunwind $DEFAULT_LIBS -ldl -lutil -lpthread -lrt " 
   if [[ x$LTO != x ]]; then
       RAW_CMD3+=" -flto"
   fi
@@ -93,7 +95,7 @@ function drive {
           echo -e "#include <stdio.h>\nconst char LOCALWRITE_MODULE=0;const size_t LOCALWRITE_MASK=0; const size_t LOCALWRITE_PATTERN=0;" | clang -x c -c -o constants.o -
       fi
       # CMD3="clang++ -flto -no-pie  -O2 $PRELINK_OBJ $SLAMP_HOOKS constants.o -o $EXE -g $LINKING_OPTS -lunwind $DEFAULT_LIBS -ldl -lutil"
-      CMD3="clang++ -no-pie  -O2 $PRELINK_OBJ $SLAMP_HOOKS -o $EXE -g $LINKING_OPTS -lunwind $DEFAULT_LIBS -ldl -lutil"
+      CMD3="clang++ -no-pie  -O2 $PRELINK_OBJ $SLAMP_HOOKS -o $EXE -g $LINKING_OPTS -lunwind $DEFAULT_LIBS -ldl -lutil  -lpthread -lrt"
       #CMD3="clang++ -no-pie  -O2 $PRELINK_OBJ $SLAMP_HOOKS -mllvm -inline-threshold=5000 -o $EXE -g $LINKING_OPTS -lunwind $DEFAULT_LIBS -ldl -lutil"
   fi
 
@@ -128,11 +130,29 @@ function drive {
   echo -e "${red}    --- Run Simulator...${nc}"
   echo $CMD4
   #time $CMD4 > /dev/null 2>&1
-  eval time $CMD4
-  if [[ $? -ne 0 ]]; then
-    echo -e "${red}    --- SIMULATION FAILED${nc}"
-    rm -f result.slamp.profile
-    exit 1
+
+  CMD4="taskset --cpu-list 7-8 $CMD4"
+  rm /dev/shm/MySharedMemory2
+  rm /dev/shm/MySharedMemory
+  taskset --cpu-list 0-6,9-27 /u/NAS_SCRATCH/ziyangx/cpf-workspace-9-master/cpf/liberty/lib/SLAMP/SLAMPcustom/consumer/build/consumer &
+  CONSUME_PID=$!
+  RUN_TIMEOUT=14400 # 4 hours
+  echo "timeout $RUN_TIMEOUT $CMD4"
+  eval regressions-watchdog $RUN_TIMEOUT slamp-custom.time $CMD4
+  # if command fail
+  if [ $? -ne 0 ]; then
+      # print in red
+      kill -9 $CONSUME_PID
+      echo -e "${red}    --- SIMULATION FAILED${nc}"
+      echo "Timed out or other problems"
+      rm -f result.slamp.profile
+      exit 1
+  else
+      # sleep for 20 seconds
+      sleep 20
+      cat deplog*.txt >> result.slamp.profile
+      rm -f deplog*.txt
+      kill -9 $CONSUME_PID
   fi
 
   if [[ x$LOCALWRITE_THREADS != x ]]; then
